# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    enable_authenticator_manager: true
    # ...

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_USER

    firewalls:
        register:
            pattern: ^/api/register
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                username_path: email
                check_path: /api/login
                success_handler: App\Security\JwtAuthenticationSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            refresh_jwt:
                check_path: /api/refresh # or, you may use the `api_refresh_token` route name

        api:
            pattern:   ^/api
            stateless: true
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/refresh # or, you may use the `api_refresh_token` route name
            logout:
                path: api_token_invalidate

        api_token_refresh:
            pattern: ^/api/refresh
            stateless: true
            refresh_jwt: ~

        products:
            pattern: ^/products
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/(login|token/refresh), roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS  }
        - { path: ^/api/profile,  roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/products, roles: ROLE_ADMIN }