/**
 * Enum for audit action types
 */
export enum AuditActionType {
  // Authentication & Access
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  LOGIN_FAILED = "LOGIN_FAILED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET = "PASSWORD_RESET",

  // CRUD Operations
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",

  // Role & Permission Management
  ROLE_CHANGED = "ROLE_CHANGED",
  PERMISSION_CHANGED = "PERMISSION_CHANGED",
  STATUS_CHANGED = "STATUS_CHANGED",

  // Inventory & Business Operations
  INVENTORY_ADJUSTED = "INVENTORY_ADJUSTED",
  BATCH_ASSIGNED = "BATCH_ASSIGNED",

  // Reports & Exports
  REPORT_EXPORTED = "REPORT_EXPORTED",
  DATA_EXPORTED = "DATA_EXPORTED",

  // Sales Operations
  SALE_CREATED = "SALE_CREATED",
  SALE_UPDATED = "SALE_UPDATED",
  SALE_CANCELLED = "SALE_CANCELLED",

  // System Actions
  CONFIGURATION_CHANGED = "CONFIGURATION_CHANGED",
  SYSTEM_ACTION = "SYSTEM_ACTION",

  // User Management
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_DEACTIVATED = "USER_DEACTIVATED",
  USER_ACTIVATED = "USER_ACTIVATED",
}
