import { Injectable, Logger } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository, IsNull } from "typeorm";
import { Cron, CronExpression } from "@nestjs/schedule";
import { MailerService } from "@nestjs-modules/mailer";
import { SalesReportsService } from "./sales-reports.service";
import { DailyReportLog } from "../entities/DailyReportLog.entity";
import { ADMIN_EMAILS } from "../constants/admin-emails.constant";
import { SalesMetrics } from "../interfaces/reports.interface";

@Injectable()
export class DailyReportService {
  private readonly logger = new Logger(DailyReportService.name);

  constructor(
    private readonly salesReportsService: SalesReportsService,
    private readonly mailerService: MailerService,
    @InjectRepository(DailyReportLog)
    private readonly dailyReportLogRepository: Repository<DailyReportLog>,
  ) {}

  @Cron(CronExpression.EVERY_DAY_AT_8AM)
  public async sendDailySalesReport(): Promise<void> {
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);

    // Check if report already sent for yesterday
    const existingLog = await this.dailyReportLogRepository.findOne({
      where: {
        reportDate: yesterday,
        deletedAt: IsNull(),
      },
    });

    if (existingLog?.sent) {
      this.logger.log(
        `Daily report for ${yesterday.toDateString()} already sent. Skipping.`,
      );
      return;
    }

    try {
      // Get daily sales summary
      const metrics =
        await this.salesReportsService.getDailySalesSummary(yesterday);

      // Send email
      await this.sendReportEmail(yesterday, metrics);

      // Mark as sent
      if (existingLog) {
        existingLog.sent = true;
        await this.dailyReportLogRepository.save(existingLog);
      } else {
        const newLog = this.dailyReportLogRepository.create({
          reportDate: yesterday,
          sent: true,
        });
        await this.dailyReportLogRepository.save(newLog);
      }

      this.logger.log(
        `Daily sales report sent for ${yesterday.toDateString()}`,
      );
    } catch (error) {
      this.logger.error(
        `Failed to send daily report for ${yesterday.toDateString()}:`,
        error,
      );
    }
  }

  private async sendReportEmail(
    date: Date,
    metrics: SalesMetrics,
  ): Promise<void> {
    const subject = `Daily Sales Report - ${date.toDateString()}`;
    const html = this.generateReportHtml(date, metrics);

    await this.mailerService.sendMail({
      to: ADMIN_EMAILS,
      subject,
      html,
    });
  }

  private generateReportHtml(date: Date, metrics: SalesMetrics): string {
    return `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #333;">Daily Sales Report</h1>
        <p><strong>Date:</strong> ${date.toDateString()}</p>
        
        <h2>Summary</h2>
        <ul>
          <li><strong>Total Revenue:</strong> ₵${metrics.totalRevenue.toFixed(2)}</li>
          <li><strong>Total Sales:</strong> ${metrics.totalSales}</li>
          <li><strong>Average Order Value:</strong> ₵${metrics.averageOrderValue.toFixed(2)}</li>
          <li><strong>Total Quantity Sold:</strong> ${metrics.totalQuantitySold}</li>
        </ul>
        
        <p>This is an automated daily report generated by the system.</p>
      </div>
    `;
  }
}
